server:
  port: 8082

spring:
  application:
    name: email-notification-service
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: email-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: |
          order.completed:dev.kornienko.email.dto.OrderCompletedEvent,
          order.failed:dev.kornienko.email.dto.OrderFailedEvent
  
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    dev.kornienko.email: DEBUG
    org.springframework.kafka: INFO