services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    mem_limit: 256mb
    cpus: "1"

  external-stub:
    image: external-http-stub-service:latest
    environment:
      SERVER_PORT: 8081
      STUB_INVENTORY_REJECT_ENABLED: true
      STUB_INVENTORY_REJECT_PROBABILITY: 0.5
      STUB_PRICING_EXCEPTION_ENABLED: true
      STUB_PRICING_EXCEPTION_PROBABILITY: 0.3
      STUB_SHIPPING_EXCEPTION_ENABLED: true
      STUB_SHIPPING_EXCEPTION_PROBABILITY: 0.3
      SPRING_THREADS_VIRTUAL_ENABLED: false
    ports:
      - "8081:8081"
    mem_limit: 256mb
    cpus: "1"

  kafka:
    image: apache/kafka:latest
    container_name: kafka

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"
        ]
      interval: 5s
      timeout: 10s
      retries: 20
    mem_limit: 512m
    cpus: "1"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    mem_limit: 128mb
    cpus: "0.5"

  email-service:
    build: ../email-notification-service
    ports:
      - "8082:8082"
    depends_on:
      kafka:
        condition: service_healthy

      mailhog:
        condition: service_started
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MAIL_HOST: mailhog
      MAIL_PORT: 1025

    mem_limit: 256m
    cpus: "1"
