server:
  port: 8082

spring:
  application:
    name: email-notification-service
  
  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: email-group
      auto-offset-reset: earliest

  
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    dev.kornienko.email: DEBUG
    org.springframework.kafka: INFO